services:
  db:
    image: postgres
    container_name: db
    hostname: db.local
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
  actors:
    container_name: actors
    build:
      dockerfile: ./Actors/Dockerfile
    hostname: actors.local
    depends_on:
      - db
    ports:
      - "8080:8080"