// <auto-generated />
using System;
using ActorsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Actors.Migrations
{
    [DbContext(typeof(ActorsDbContext))]
    [Migration("20240201195748_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActorsService.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BornDate")
                        .HasColumnType("date")
                        .HasColumnName("born_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("ListOfMovies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("list_of_movies");

                    b.HasKey("Id");

                    b.ToTable("actors");

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 0",
                            LastName = "Last Name 0",
                            ListOfMovies = "Movies 0"
                        },
                        new
                        {
                            Id = 10001,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 1",
                            LastName = "Last Name 1",
                            ListOfMovies = "Movies 1"
                        },
                        new
                        {
                            Id = 10002,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 2",
                            LastName = "Last Name 2",
                            ListOfMovies = "Movies 2"
                        },
                        new
                        {
                            Id = 10003,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 3",
                            LastName = "Last Name 3",
                            ListOfMovies = "Movies 3"
                        },
                        new
                        {
                            Id = 10004,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 4",
                            LastName = "Last Name 4",
                            ListOfMovies = "Movies 4"
                        },
                        new
                        {
                            Id = 10005,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 5",
                            LastName = "Last Name 5",
                            ListOfMovies = "Movies 5"
                        },
                        new
                        {
                            Id = 10006,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 6",
                            LastName = "Last Name 6",
                            ListOfMovies = "Movies 6"
                        },
                        new
                        {
                            Id = 10007,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 7",
                            LastName = "Last Name 7",
                            ListOfMovies = "Movies 7"
                        },
                        new
                        {
                            Id = 10008,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 8",
                            LastName = "Last Name 8",
                            ListOfMovies = "Movies 8"
                        },
                        new
                        {
                            Id = 10009,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 9",
                            LastName = "Last Name 9",
                            ListOfMovies = "Movies 9"
                        },
                        new
                        {
                            Id = 10010,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 10",
                            LastName = "Last Name 10",
                            ListOfMovies = "Movies 10"
                        },
                        new
                        {
                            Id = 10011,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 11",
                            LastName = "Last Name 11",
                            ListOfMovies = "Movies 11"
                        },
                        new
                        {
                            Id = 10012,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 12",
                            LastName = "Last Name 12",
                            ListOfMovies = "Movies 12"
                        },
                        new
                        {
                            Id = 10013,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 13",
                            LastName = "Last Name 13",
                            ListOfMovies = "Movies 13"
                        },
                        new
                        {
                            Id = 10014,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 14",
                            LastName = "Last Name 14",
                            ListOfMovies = "Movies 14"
                        },
                        new
                        {
                            Id = 10015,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 15",
                            LastName = "Last Name 15",
                            ListOfMovies = "Movies 15"
                        },
                        new
                        {
                            Id = 10016,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 16",
                            LastName = "Last Name 16",
                            ListOfMovies = "Movies 16"
                        },
                        new
                        {
                            Id = 10017,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 17",
                            LastName = "Last Name 17",
                            ListOfMovies = "Movies 17"
                        },
                        new
                        {
                            Id = 10018,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 18",
                            LastName = "Last Name 18",
                            ListOfMovies = "Movies 18"
                        },
                        new
                        {
                            Id = 10019,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 19",
                            LastName = "Last Name 19",
                            ListOfMovies = "Movies 19"
                        },
                        new
                        {
                            Id = 10020,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 20",
                            LastName = "Last Name 20",
                            ListOfMovies = "Movies 20"
                        },
                        new
                        {
                            Id = 10021,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 21",
                            LastName = "Last Name 21",
                            ListOfMovies = "Movies 21"
                        },
                        new
                        {
                            Id = 10022,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 22",
                            LastName = "Last Name 22",
                            ListOfMovies = "Movies 22"
                        },
                        new
                        {
                            Id = 10023,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 23",
                            LastName = "Last Name 23",
                            ListOfMovies = "Movies 23"
                        },
                        new
                        {
                            Id = 10024,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 24",
                            LastName = "Last Name 24",
                            ListOfMovies = "Movies 24"
                        },
                        new
                        {
                            Id = 10025,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 25",
                            LastName = "Last Name 25",
                            ListOfMovies = "Movies 25"
                        },
                        new
                        {
                            Id = 10026,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 26",
                            LastName = "Last Name 26",
                            ListOfMovies = "Movies 26"
                        },
                        new
                        {
                            Id = 10027,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 27",
                            LastName = "Last Name 27",
                            ListOfMovies = "Movies 27"
                        },
                        new
                        {
                            Id = 10028,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 28",
                            LastName = "Last Name 28",
                            ListOfMovies = "Movies 28"
                        },
                        new
                        {
                            Id = 10029,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 29",
                            LastName = "Last Name 29",
                            ListOfMovies = "Movies 29"
                        },
                        new
                        {
                            Id = 10030,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 30",
                            LastName = "Last Name 30",
                            ListOfMovies = "Movies 30"
                        },
                        new
                        {
                            Id = 10031,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 31",
                            LastName = "Last Name 31",
                            ListOfMovies = "Movies 31"
                        },
                        new
                        {
                            Id = 10032,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 32",
                            LastName = "Last Name 32",
                            ListOfMovies = "Movies 32"
                        },
                        new
                        {
                            Id = 10033,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 33",
                            LastName = "Last Name 33",
                            ListOfMovies = "Movies 33"
                        },
                        new
                        {
                            Id = 10034,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 34",
                            LastName = "Last Name 34",
                            ListOfMovies = "Movies 34"
                        },
                        new
                        {
                            Id = 10035,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 35",
                            LastName = "Last Name 35",
                            ListOfMovies = "Movies 35"
                        },
                        new
                        {
                            Id = 10036,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 36",
                            LastName = "Last Name 36",
                            ListOfMovies = "Movies 36"
                        },
                        new
                        {
                            Id = 10037,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 37",
                            LastName = "Last Name 37",
                            ListOfMovies = "Movies 37"
                        },
                        new
                        {
                            Id = 10038,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 38",
                            LastName = "Last Name 38",
                            ListOfMovies = "Movies 38"
                        },
                        new
                        {
                            Id = 10039,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 39",
                            LastName = "Last Name 39",
                            ListOfMovies = "Movies 39"
                        },
                        new
                        {
                            Id = 10040,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 40",
                            LastName = "Last Name 40",
                            ListOfMovies = "Movies 40"
                        },
                        new
                        {
                            Id = 10041,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 41",
                            LastName = "Last Name 41",
                            ListOfMovies = "Movies 41"
                        },
                        new
                        {
                            Id = 10042,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 42",
                            LastName = "Last Name 42",
                            ListOfMovies = "Movies 42"
                        },
                        new
                        {
                            Id = 10043,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 43",
                            LastName = "Last Name 43",
                            ListOfMovies = "Movies 43"
                        },
                        new
                        {
                            Id = 10044,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 44",
                            LastName = "Last Name 44",
                            ListOfMovies = "Movies 44"
                        },
                        new
                        {
                            Id = 10045,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 45",
                            LastName = "Last Name 45",
                            ListOfMovies = "Movies 45"
                        },
                        new
                        {
                            Id = 10046,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 46",
                            LastName = "Last Name 46",
                            ListOfMovies = "Movies 46"
                        },
                        new
                        {
                            Id = 10047,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 47",
                            LastName = "Last Name 47",
                            ListOfMovies = "Movies 47"
                        },
                        new
                        {
                            Id = 10048,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 48",
                            LastName = "Last Name 48",
                            ListOfMovies = "Movies 48"
                        },
                        new
                        {
                            Id = 10049,
                            BornDate = new DateOnly(2000, 1, 2),
                            FirstName = "First Name 49",
                            LastName = "Last Name 49",
                            ListOfMovies = "Movies 49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
